version: '3.8'

services:
  web:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER:-POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-POSTGRES_PASSWORD}
      POSTGRES_HOST: db

  db:
    image: postgres:13
    container_name: my-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER:-POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
